export const ENV = {
  TIMBU_BASE_URL: process.env.EXPO_PUBLIC_TIMBU_BASE_URL ?? "",
  TIMBU_API_KEY: process.env.EXPO_PUBLIC_TIMBU_API_KEY ?? "",
  TIMBU_APP_ID: process.env.EXPO_PUBLIC_TIMBU_APP_ID ?? "",
  TIMBU_ORG_ID: process.env.EXPO_PUBLIC_TIMBU_ORG_ID ?? "",
  TIMBU_PROXY_BASE_URL: process.env.EXPO_PUBLIC_TIMBU_PROXY_BASE_URL,
};
